[[session]]
name = "Home ğŸ "
path = "~"

[[session]]
name = "Neovim Conf ğŸ’»"
path = "~/.config/nvim"

[[session]]
name = "Notes ğŸ“"
path = "~/Notes/aquila-notes/"

[[session]]
name = "Vault Notes ğŸ“ğŸ”"
path = "~/Notes/aquila-notes/vault-notes"
